### ISSUE TITLE
Minerals4EU is wrong title here

### ISSUE THREAD

**Issue by nmtoken** [GeoEra-GIP/Raw-Materials#1]
The minerals project in the Raw Materials Theme of GeoERA is not called _Minerals4EU_ it's called _Mineral Intelligence for Europe (Mintell4EU)_

[Minerals4EU](http://www.minerals4eu.eu/) is the name of a previous project

**Comment by nmtoken** [comment]
Minerals4EU ran from 1 September 2013 to 31 August 2015

ref: https://cordis.europa.eu/project/rcn/109373/factsheet/en

**Comment by ManuelFilipeSantos65** [comment]
Hello James. 
Thank you for your comment. We didn't refer to a specific GeoERA project. This repository is supposed to address issues related to M4EU/PROSUM DB and existing harvesting process. All GeoERA project raw material theme have a strong connection to this database. If possible, we suggest this title to be changed, e.g. to "M4EU DB". What do you think?

**Comment by nmtoken** [comment]
The Mintell project data will deviate quite a bit I think from the M4EU/PROSUM/EURARE DB structure due to the aggregated nature of the data.  It doesn't fit with the current ERML model very well at all.

But I misunderstood the reason for the Minerals4EU topic, I was thinking that this wiki etc was for projects that need support, under the current GeoERA-GIP activities.  So let's keep the title and add a new one for Mintell4EU.

On Minerals4EU there was already support material on the GEUS SVN repo (http://data.geus.dk/svn/m4eu/), though this appears now to be migrated to GitLab (https://geusgitlab.geus.dk/m4eu).
